spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: cook-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/knusrae_db}
    username: ${DB_USERNAME:knusrae_user}
    password: ${DB_PASSWORD:CookRecipes999!@#}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:50MB}
app:
  storage:
    local:
      base-dir: ${STORAGE_BASE_DIR:C:/JangJinSeok/test/uploads}
      public-base-url: ${STORAGE_PUBLIC_BASE_URL:http://localhost:8082/uploads}

server:
  port: 8082