spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name : cook-service
  datasource:
    url: jdbc:postgresql://localhost:5432/knusrae_db
    username: knusrae_user
    password: CookRecipes999!@#
  jpa:
    hibernate:
      ddl-auto: update # dev : update, prd : validate or none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        highlight_sql: true
#        use_sql_comments: true
#    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
app:
  storage:
    local:
      base-dir: C:/JangJinSeok/test/uploads         # ← 실제 저장 폴더
      public-base-url: http://localhost:8082/uploads # ← 브라우저에서 접근할 URL

server:
  port: 8082