spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name: member-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/knusrae_db}
    username: ${DB_USERNAME:knusrae_user}
    password: ${DB_PASSWORD:CookRecipes999!@#}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
